// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// extract_words
NumericMatrix extract_words(CharacterVector words, CharacterVector vectors_file, bool verbose, int report_every);
RcppExport SEXP _cbn_extract_words(SEXP wordsSEXP, SEXP vectors_fileSEXP, SEXP verboseSEXP, SEXP report_everySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type words(wordsSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type vectors_file(vectors_fileSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type report_every(report_everySEXP);
    rcpp_result_gen = Rcpp::wrap(extract_words(words, vectors_file, verbose, report_every));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cbn_extract_words", (DL_FUNC) &_cbn_extract_words, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_cbn(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
