# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

extract_words <- function(p, width, cc_path, verbose, report_every) {
    .Call('_cbn_extract_words', PACKAGE = 'cbn', p, width, cc_path, verbose, report_every)
}

